// script.js for ContentPilotAI
// -----------------------------------
// Configuration
// IMPORTANT: Put your REAL OpenAI API key here.
// In a real production app, this should be hidden behind a backend (like Node.js)
const OPENAI_API_KEY = "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";
const OPENAI_API_URL = "https://api.openai.com/v1/chat/completions";

// Utility: simple fetch wrapper for OpenAI Chat Completion
async function callOpenAI(messages) {
  if (!OPENAI_API_KEY || OPENAI_API_KEY === "YOUR_OPENAI_API_KEY_HERE") {
    throw new Error("API Key is missing! You need to open script.js and put your OpenAI API Key in the code.");
  }

  const response = await fetch(OPENAI_API_URL, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${OPENAI_API_KEY}`,
    },
    body: JSON.stringify({
      model: "gpt-3.5-turbo",
      messages,
      temperature: 0.7,
    }),
  });
  if (!response.ok) {
    const err = await response.json();
    throw new Error(`OpenAI error: ${err.error?.message || response.statusText}`);
  }
  const data = await response.json();
  return data.choices[0].message.content.trim();
}

// Language handling
let currentLang = "en"; // default
function updateLanguage() {
  document.querySelectorAll("[data-en]").forEach((el) => {
    const text = el.getAttribute(`data-${currentLang}`) || el.textContent;
    if (el.tagName === "INPUT" || el.tagName === "TEXTAREA") {
      el.placeholder = text;
    } else {
      el.textContent = text;
    }
  });
}

document.getElementById("langSelect").addEventListener("change", (e) => {
  currentLang = e.target.value;
  updateLanguage();
});
// Initialise language on load
updateLanguage();

// Purchase button – Stripe payment link integration
// ----------------------------------------------------
// STRIPE CONFIGURATION:
// 1. Go to your Stripe Dashboard -> Payment Links.
// 2. Create a new link for your product (€49).
// 3. Paste the URL generated by Stripe below.
// 4. In Stripe, set the "After payment" setting to redirect the user back to your website so they can Register.
const BUY_URL = "https://buy.stripe.com/14A8wHblIbxjcR397m8g000";

if (document.getElementById("buyBtn")) {
  document.getElementById("buyBtn").addEventListener("click", () => {
    // Redirects directly to your real Stripe checkout link
    window.location.href = BUY_URL;
  });
}

// Utility: Copy to Clipboard
function copyText(elementId) {
  const el = document.getElementById(elementId);
  el.select();
  document.execCommand("copy");

  // Quick visual feedback
  const btn = el.nextElementSibling;
  const originalText = btn.textContent;
  btn.textContent = "Copied!";
  setTimeout(() => { btn.textContent = originalText; }, 2000);
}

// Simple UI feedback
function showLoading(btn) {
  btn.disabled = true;
  const original = btn.textContent;
  btn.textContent = "Loading...";
  return () => {
    btn.disabled = false;
    btn.textContent = original;
  };
}

// Instagram Captions
document.getElementById("generateCaptionsBtn").addEventListener("click", async () => {
  const theme = document.getElementById("captionTheme").value.trim();
  const tone = document.getElementById("captionTone").value; // Gets tone (casual, professional, etc)

  if (!theme) return alert("Please enter a theme.");

  const btn = document.getElementById("generateCaptionsBtn");
  const done = showLoading(btn);

  const prompt = `Create 30 short, catchy Instagram captions about the following theme: "${theme}". 
The tone of voice MUST BE: ${tone}. 
Keep each caption under 100 characters. Include emojis and a few relevant hashtags.`;
  try {
    const result = await callOpenAI([{ role: "user", content: prompt }]);
    document.getElementById("captionsOutput").value = result;
  } catch (err) {
    console.error(err);
    alert(err.message);
  } finally {
    done();
  }
});

// Email Summarizer
document.getElementById("summarizeEmailBtn").addEventListener("click", async () => {
  const email = document.getElementById("emailText").value.trim();
  if (!email) return alert("Please paste an email.");

  const btn = document.getElementById("summarizeEmailBtn");
  const done = showLoading(btn);

  const prompt = `Summarize the following email in 3-5 concise sentences, keeping the main points and tone. Email:\n\n${email}`;
  try {
    const result = await callOpenAI([{ role: "user", content: prompt }]);
    document.getElementById("emailSummary").value = result;
  } catch (err) {
    console.error(err);
    alert(err.message);
  } finally {
    done();
  }
});

// Comment Bot
document.getElementById("replyCommentBtn").addEventListener("click", async () => {
  const comment = document.getElementById("commentText").value.trim();
  if (!comment) return alert("Please paste a comment.");

  const btn = document.getElementById("replyCommentBtn");
  const done = showLoading(btn);

  const prompt = `Write a friendly, short (max 30 words) reply to the following Instagram comment using a warm brand voice. Comment: "${comment}"`;
  try {
    const result = await callOpenAI([{ role: "user", content: prompt }]);
    document.getElementById("commentReply").value = result;
  } catch (err) {
    console.error(err);
    alert(err.message);
  } finally {
    done();
  }
});

// SEO Blog Generator
document.getElementById("generateBlogBtn").addEventListener("click", async () => {
  const keyword = document.getElementById("blogKeyword").value.trim();
  if (!keyword) return alert("Please enter a keyword.");

  const btn = document.getElementById("generateBlogBtn");
  const done = showLoading(btn);

  const prompt = `Write a comprehensive, SEO-optimized blog article about "${keyword}". 
Include a catchy H1 title, an introduction, 3 main sections with H2 headers, and a conclusion.
Make it engaging, informative, and formatted in clean markdown.`;
  try {
    const result = await callOpenAI([{ role: "user", content: prompt }]);
    document.getElementById("blogOutput").value = result;
  } catch (err) {
    console.error(err);
    alert(err.message);
  } finally {
    done();
  }
});

// Viral Video Script
document.getElementById("generateScriptBtn").addEventListener("click", async () => {
  const topic = document.getElementById("scriptTopic").value.trim();
  const platform = document.getElementById("scriptPlatform").value;
  if (!topic) return alert("Please enter a topic.");
  
  const btn = document.getElementById("generateScriptBtn");
  const done = showLoading(btn);

  const prompt = `Write a high-retention, engaging video script for ${platform} about "${topic}".
Include:
1. A strong 3-second hook to grab attention.
2. Fast-paced body content (keep it concise).
3. A clear Call to Action (CTA) at the end.
Provide visual cues in brackets like [Zoom in] or [Point to text].`;
  try {
    const result = await callOpenAI([{ role: "user", content: prompt }]);
    document.getElementById("scriptOutput").value = result;
  } catch (err) {
    console.error(err);
    alert(err.message);
  } finally {
    done();
  }
});

// Sales Email Writer
document.getElementById("generateSalesEmailBtn").addEventListener("click", async () => {
  const product = document.getElementById("productName").value.trim();
  const audience = document.getElementById("targetAudience").value.trim();
  if (!product || !audience) return alert("Please fill in both Product and Audience fields.");
  
  const btn = document.getElementById("generateSalesEmailBtn");
  const done = showLoading(btn);

  const prompt = `Write a high-converting cold sales email selling "${product}" to "${audience}".
The email should be:
- Short and punchy (under 150 words).
- Focus on the pain points of the audience and how the product solves them.
- Include a catchy, non-clickbaity subject line.
- End with a low-friction call to action (e.g. asking for a quick chat).`;
  try {
    const result = await callOpenAI([{ role: "user", content: prompt }]);
    document.getElementById("salesEmailOutput").value = result;
  } catch (err) {
    console.error(err);
    alert(err.message);
  } finally {
    done();
  }
});

// --- Handle Fake Auth & Dashboard Views ---
const authModal = document.getElementById("authModal");
const loginBtn = document.getElementById("loginBtn");
const registerBtn = document.getElementById("registerBtn");
const closeModalBtn = document.querySelector(".close-modal");
const submitAuthBtn = document.getElementById("submitAuthBtn");
const modalTitle = document.getElementById("modalTitle");
const authEmail = document.getElementById("authEmail");
const authPassword = document.getElementById("authPassword");
const authError = document.getElementById("authError");

const landingView = document.getElementById("landingView");
const dashboardView = document.getElementById("dashboardView");
const authButtonsOut = document.getElementById("authButtonsOut");
const authButtonsIn = document.getElementById("authButtonsIn");
const userEmailDisplay = document.getElementById("userEmailDisplay");
const logoutBtn = document.getElementById("logoutBtn");

let isLoginMode = true;

// Check existing session
function checkAuth() {
  const user = localStorage.getItem("contentpilot_user");
  if (user) {
    // Logged in
    landingView.classList.add("hidden");
    dashboardView.classList.remove("hidden");
    authButtonsOut.classList.add("hidden");
    authButtonsIn.classList.remove("hidden");
    userEmailDisplay.textContent = user;
  } else {
    // Logged out
    landingView.classList.remove("hidden");
    dashboardView.classList.add("hidden");
    authButtonsOut.classList.remove("hidden");
    authButtonsIn.classList.add("hidden");
  }
}

// Open modal
function openModal(mode) {
  isLoginMode = mode === "login";
  modalTitle.textContent = isLoginMode ? "Login" : "Register";
  submitAuthBtn.textContent = isLoginMode ? "Login" : "Create Account";
  authError.classList.add("hidden");
  authEmail.value = "";
  authPassword.value = "";
  authModal.classList.remove("hidden");
}

if (loginBtn) loginBtn.addEventListener("click", () => openModal("login"));

if (closeModalBtn) closeModalBtn.addEventListener("click", () => {
  authModal.classList.add("hidden");
});

// Check if Stripe redirected here to register
if (window.location.hash === "#register") {
  openModal("register");
  history.replaceState(null, null, ' '); // Clean URL
}

// Handle Login/Register Submit
if (submitAuthBtn) submitAuthBtn.addEventListener("click", () => {
  const email = authEmail.value.trim();
  const pass = authPassword.value.trim();

  if (!email || !pass) {
    authError.textContent = "Please fill all fields.";
    authError.classList.remove("hidden");
    return;
  }

  if (isLoginMode) {
    // LOGIN LOGIC
    // Check if it's the admin or a previously registered user in this browser
    const savedUser = JSON.parse(localStorage.getItem("registered_account"));
    
    const isAdmin = email === "admin" && pass === "J7$kPz8!nQwT4X@b2";
    const isSavedUser = savedUser && email === savedUser.email && pass === savedUser.pass;

    if (isAdmin || isSavedUser) {
      localStorage.setItem("contentpilot_user", email);
      authModal.classList.add("hidden");
      checkAuth();
    } else {
      authError.textContent = "Invalid email or password. You must register first.";
      authError.classList.remove("hidden");
    }
  } else {
    // REGISTER LOGIC (after paying)
    localStorage.setItem("registered_account", JSON.stringify({ email, pass }));
    localStorage.setItem("contentpilot_user", email);
    authModal.classList.add("hidden");
    checkAuth();
  }
});

// Logout
if (logoutBtn) logoutBtn.addEventListener("click", () => {
  localStorage.removeItem("contentpilot_user");
  checkAuth();
});

// Init
checkAuth();
